const fileTypeIcons = {
  'js': { icon: '📜', color: '#f7df1e', class: 'file-icon-js' },
  'jsx': { icon: '📜', color: '#f7df1e', class: 'file-icon-js' },
  'mjs': { icon: '📜', color: '#f7df1e', class: 'file-icon-js' },
  'ts': { icon: '📘', color: '#3178c6', class: 'file-icon-ts' },
  'tsx': { icon: '📘', color: '#3178c6', class: 'file-icon-ts' },
  'py': { icon: '🐍', color: '#3776ab', class: 'file-icon-py' },
  'pyc': { icon: '🐍', color: '#3776ab', class: 'file-icon-py' },
  'pyw': { icon: '🐍', color: '#3776ab', class: 'file-icon-py' },
  'html': { icon: '🌐', color: '#e34c26', class: 'file-icon-html' },
  'htm': { icon: '🌐', color: '#e34c26', class: 'file-icon-html' },
  'css': { icon: '🎨', color: '#563d7c', class: 'file-icon-css' },
  'scss': { icon: '🎨', color: '#563d7c', class: 'file-icon-css' },
  'sass': { icon: '🎨', color: '#563d7c', class: 'file-icon-css' },
  'less': { icon: '🎨', color: '#563d7c', class: 'file-icon-css' },
  'json': { icon: '📋', color: '#5a5a5a', class: 'file-icon-json' },
  'md': { icon: '📝', color: '#083fa1', class: 'file-icon-md' },
  'markdown': { icon: '📝', color: '#083fa1', class: 'file-icon-md' },
  'txt': { icon: '📄', color: '#6b6b6b', class: 'file-icon-txt' },
  'log': { icon: '📄', color: '#6b6b6b', class: 'file-icon-txt' },
  'c': { icon: '©️', color: '#555555', class: 'file-icon-c' },
  'h': { icon: '©️', color: '#555555', class: 'file-icon-c' },
  'cpp': { icon: '➕', color: '#00599c', class: 'file-icon-cpp' },
  'hpp': { icon: '➕', color: '#00599c', class: 'file-icon-cpp' },
  'cc': { icon: '➕', color: '#00599c', class: 'file-icon-cpp' },
  'java': { icon: '☕', color: '#007396', class: 'file-icon-java' },
  'cs': { icon: '♯', color: '#239120', class: 'file-icon-cs' },
  'php': { icon: '🐘', color: '#777bb4', class: 'file-icon-php' },
  'rb': { icon: '💎', color: '#cc342d', class: 'file-icon-rb' },
  'go': { icon: '🐹', color: '#00add8', class: 'file-icon-go' },
  'rs': { icon: '🦀', color: '#dea584', class: 'file-icon-rs' },
  'swift': { icon: '🕊️', color: '#fa7343', class: 'file-icon-swift' },
  'kt': { icon: '🅺', color: '#7f52ff', class: 'file-icon-kt' },
  'kts': { icon: '🅺', color: '#7f52ff', class: 'file-icon-kt' },
  'xml': { icon: '📰', color: '#e67e22', class: 'file-icon-xml' },
  'yaml': { icon: '⚙️', color: '#cb171e', class: 'file-icon-yaml' },
  'yml': { icon: '⚙️', color: '#cb171e', class: 'file-icon-yaml' },
  'sh': { icon: '🐚', color: '#4eaa25', class: 'file-icon-sh' },
  'bash': { icon: '🐚', color: '#4eaa25', class: 'file-icon-sh' },
  'zsh': { icon: '🐚', color: '#4eaa25', class: 'file-icon-sh' },
  'sql': { icon: '🗄️', color: '#f29111', class: 'file-icon-sql' },
  'env': { icon: '🔐', color: '#ecd53f', class: 'file-icon-env' },
  'ini': { icon: '⚙️', color: '#6b6b6b', class: 'file-icon-txt' },
  'conf': { icon: '⚙️', color: '#6b6b6b', class: 'file-icon-txt' },
  'config': { icon: '⚙️', color: '#6b6b6b', class: 'file-icon-txt' },
  'png': { icon: '🖼️', color: '#83CD29', class: 'file-icon-txt' },
  'jpg': { icon: '🖼️', color: '#83CD29', class: 'file-icon-txt' },
  'jpeg': { icon: '🖼️', color: '#83CD29', class: 'file-icon-txt' },
  'gif': { icon: '🖼️', color: '#83CD29', class: 'file-icon-txt' },
  'svg': { icon: '🎨', color: '#FFB13B', class: 'file-icon-txt' },
  'pdf': { icon: '📕', color: '#F40F02', class: 'file-icon-txt' },
  'db': { icon: '🗄️', color: '#f29111', class: 'file-icon-sql' },
  'sqlite': { icon: '🗄️', color: '#f29111', class: 'file-icon-sql' }
};

export const getFileIcon = (filename) => {
  const ext = filename.split('.').pop().toLowerCase();
  const iconData = fileTypeIcons[ext] || { icon: '📄', color: '#6b6b6b', class: 'file-icon-txt' };
  return `<span class="${iconData.class}" style="color: ${iconData.color}">${iconData.icon}</span>`;
};

export const detectLanguage = (fileName) => {
  const ext = fileName.split('.').pop().toLowerCase();
  const languages = {
    'js': 'javascript',
    'jsx': 'javascript',
    'mjs': 'javascript',
    'ts': 'typescript',
    'tsx': 'typescript',
    'html': 'html',
    'htm': 'html',
    'css': 'css',
    'scss': 'scss',
    'sass': 'sass',
    'less': 'less',
    'py': 'python',
    'java': 'java',
    'cpp': 'cpp',
    'c': 'c',
    'cs': 'csharp',
    'json': 'json',
    'xml': 'xml',
    'md': 'markdown',
    'markdown': 'markdown',
    'sql': 'sql',
    'php': 'php',
    'rb': 'ruby',
    'go': 'go',
    'rs': 'rust',
    'swift': 'swift',
    'kt': 'kotlin',
    'sh': 'shell',
    'bash': 'shell',
    'zsh': 'shell',
    'yaml': 'yaml',
    'yml': 'yaml'
  };
  return languages[ext] || 'plaintext';
};
